### ISSUE TITLE
Ch 1: Team Slipper Lobster

### ISSUE THREAD

**Issue by jcvdav** [eco-detectives/primer_of_ecology_r#6]
Hi @phoeberacine , @julawson , and @ignacia-rivera 

Looks like the other two teams are a bit ahead of us, so I thought I'd reach out and propose two workflows to tackle this first chapter.

# Workflow 1 - Same as everyone else's

- Each week, one of us creates a copy of the [chapter prepared by Casey](https://github.com/eco-detectives/primer_of_ecology_r/blob/master/ch1/chapter_1_starter.Rmd) and renames it as `CH#_slipper_lobster` or something like that
- We can either split the tasks by sections or have everyone do all sections

# Workflow 2 - Branching / merging

- I would create a branch other than `master` in this repo, for example `slipper`
- We can work on this branch while being isolated from teams nudi and sucker (short for lumpsucker, as coined by @couture322)
- Every week (or when needed) we will bring in the new chapter Casey creates by merging from `master`
- After we've done our part, we will then merge into `master` so that everyone else can see our code

This second approach is a bit more complicated, but it's a great way to keep on learning how to use GH for collaboration, where we many times want to isolate our code from everyone elses in case we break something! haha

Let me know if you'd like approach 1 or 2 and I'll set everyting up for this first week!

**Comment by phoeberacine** [comment]
I'm not a very experienced GitHub user except for my own work, but I'm
willing to try 2 if you think it's a little more organized.

**Comment by ignacia-rivera** [comment]
I will also be willing to try the branching. I've done it before but a long time ago. 

I think we should also decide on whether we want to (a) split sections within a chapter or (b) having everyone do all sections. Are we all gonna work on the same .rmd? If everyone is doing all the sections, it could be less messy to be each of us working on our own. But I guess we can also include "chunks" per person and section in one .rmd and merge our progress (at the end that's the idea with GitHub no?)

**Comment by jcvdav** [comment]
I think we can start it simple by not using branching. We can always change to the branching approach if we feel like we've got the grasp of it.

**We should all work on the same, single RMD file**. I think one of objectives of this is to get more familiar with GH and R programming, and using single files is the best way to go. As you suggest, we can use chunks per person, as in Casey's example [here](https://github.com/eco-detectives/primer_of_ecology_r/issues/2#issue-462860855). This is good practice, because when "working on our own, separate scripts / Rmd" we might miss global changes that affect the dependency of everyone else's code.

I can set up our first chapter and will ping you once it's ready, so that we can all start adding our own chunks / distributiing different parts of code to work on.

**Comment by phoeberacine** [comment]
Sounds great! Thank Juanca!

**Comment by jcvdav** [comment]
Ok, I've copied the Rmd template that Casey created. If you clone (or pull) the repo, you should find it under [`ch1/chapter_1_team_lobster.Rmd`](https://github.com/eco-detectives/primer_of_ecology_r/blob/master/ch1/chapter_1_team_lobster.Rmd). As proposed by Ignacia, the best way to go might be to copy-paste the chunks of code within the Rmd file and add your name using a comment. We're set!

Let me know if something's not working for you and we can figure it out!

**Comment by jcvdav** [comment]
Hi team - 

I've updated the repo with my version (for the first two sections) of the code. Feel free to go over it and let me know if you have any questions.

I did not do the last parts because, in the end, it gets to the "simulations with a function" section, which is what I would have done (except for the use of `base` plot).
